### ISSUE TITLE
Besoin d'aide accompagnement

### ISSUE THREAD

**Issue by Bibiche-35** [BTS-SIO-STMALO/soutien-technique#1]
Bonjour à tous,

J'ai passé la semaine à faire l'analyse des besoins et comprendre le projet du stage (diagramme réalisé, structure basse de données à finaliser ect ...)

Voir présentation du projet sur ce document : [https://drive.google.com/file/d/1_NnCMXR-MvfdXNMnU0ufXuUV5MNZ7EEx/view?usp=sharing]

Mais j'aimerais avoir une orientation ou un accompagnement, je suis beaucoup laissé en autonomie sur le projet (Point hebdomadaire, l'autonomie ne me déplait pas) mais j'ai besoin de consulter, réfléchir aux orientations avec expert, faisabilité sur les 10 semaines, appui sur CRM open source, réflexion des outils déjà existants ? 

Nos 3 mois de formation m'ont permis d'appréhender des langages de programmation mais pas sur la structure ou l'architecture technique d'un projet... 

Quelqu'un aurait il 30 min à me consacrer? 
Quelles sont vos disponibilités ? 

Merci d'avance, 
Fabrice

**Comment by mathilderenversade** [comment]
Bonjour Fabrice, 

J'ai pris connaissance de ton message et j'ai lu le document. Qu'est-ce qui te bloque ? Quelles sont les questions précises que tu te poses ? De ce que je comprends du projet, il y a beaucoup de choses que tu peux d'ores et déjà faire à ce stade, comme par exemple la rédaction du cahier des charges et la conception des maquettes fonctionnelles.

**Comment by Bibiche-35** [comment]
Bonjour Mathilde, 
Comme expliqué ci dessus, Ma demande était un petit entretien de 30min max... 
Afin de voir si mes orientations et la compatibilité du projet est en adéquation avec le délai et la réalisation. (Manque de recul sur tout ça et les solutions qui seront choisies)
Je ne peux pas faire plus clair j'ai besoin d'accompagnement.
--> Dernière version du fichier : https://drive.google.com/file/d/1_NnCMXR-MvfdXNMnU0ufXuUV5MNZ7EEx/view?usp=sharing
