### ISSUE TITLE
Problème d'internationalisation du site tekxia.com

### ISSUE THREAD

**Issue by jpicard22** [BTS-SIO-STMALO/soutien-technique#2]
Bonjour,

Je travaille sur le Framework Symfony 4.4
 
Je requière un soutien technique concernant plusieurs problèmes qui semblent très certainement liés. Mon premier soucis est lorsqu'un nouvel utilisateur se connecte sur le site tekxia.com et va sur le formulaire de contact, une erreur apparait lorsqu'il le valide. 

`Argument 1 passed to App\Entity\Leads::setLeadsLang() must be of the type string, null given, called in D:\Tekxia-recaptcha\symf_txa-com\src\Controller\TekxiaController.php on line 103`

Le formulaire n'enregistre pas la langue automatiquement. Il faut que l'utilisateur clique sur le drapeau pour que la langue soit enregistrée et rentrée dans la base de données. 

Ma base de données est bien connectée et les paramètres semblent corrects. 

Autre problème, je n’ai pas les pages www.tekxia.com/fr, www.tekxia.com/en, www.tekxia.com/fr/contact,... 

La page web ne reconnait pas automatiquement la langue. J'ai l'erreur ci dessous qui s'inscrit : 

`No route found for "GET /fr"`

J'ai utilisé les liens suivants pour essayer de me sortir de ce problème : 

[https://symfony.com/doc/current/translation/locale.html#setting-a-default-locale](url)

[https://symfony.com/doc/current/session/locale_sticky_session.html](url)

[https://nouvelle-techno.fr/actualites/live-coding-creer-un-site-multilingue-avec-symfony-4](url)

[https://gmanier.com/project/2/reecriture-d-url-pour-la-langue-locale-par-defaut-sous-symfony-4](url)

[https://www.grafikart.fr/forum/topics/31229](url)

et encore bien d'autres ... 

J'ai voulu forcer la variable locale pour la passer en français avec ce code suivant mais ça affichait dans la base de données   g~ dans la colonne de la langue. Que ce soit en français ou en anglais. 

` if ($form->isSubmitted() && $form->isValid()) {

        $session=$request->getSession();

        $locale='fr';

        $locale= $session ->get('_locale');

        
            if(!($locale='fr' | $locale='en')){

            }`

J'ai voulu adapter ce bout de code ci-dessous mais sans succès.

`
         //  if($locale != null)

         //  {

               //  $this->get('session')->set('_locale', $locale);

         //  }
`

Je vais vous mettre les fichiers ci-dessous : 

symf_txa-com\src\Controller\TekxiaController.php
symf_txa-com\config\services.yaml
symf_txa-com\config\packages\translation.yaml
symf_txa-com\src\EventSubscriber\UserLocaleSubscriber.php
symf_txa-com\src\EventSubscriber\LocaleSubscriber.php

La partie de base.html.twig qui correspond aux drapeaux. 

**TekxiaController.php**

`<?php

namespace App\Controller;

use App\Entity\Leads;
use App\Form\UserRegistrationFormType;

use App\Notification\ContactNotification;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;
use function mysql_xdevapi\getSession;

class TekxiaController extends AbstractController
{
    /**
     * @Route("/tekxia", name="tekxia")
     */
    public function index()
    {
        return $this->render('tekxia/produits.html.twig', [
            'controller_name' => 'TekxiaController',
        ]);
    }

    /**
     * @Route("/", name="home")
     */
    public function home()
    {

        return $this->render('tekxia/about.html.twig', [

        ]);
    }

    /**
     * @Route("/applications", name="applications")
     */
    public function applications()
    {

        return $this->render('tekxia/applications.html.twig', [

        ]);
    }

    /**
     * @Route("/contact", name="contact")
     */

    public function contact(Request $request, \Swift_Mailer $mailer, ContactNotification $notification, TranslatorInterface $translator)
    {

        $translated = $translator->trans('Nom');
        $translated = $translator->trans('Email');
        $translated = $translator->trans('Sujet');
        $translated = $translator->trans('Code de sécurité');
        $translated = $translator->trans('Votre sujet *');
        $translated = $translator->trans('Recevoir le flyer SPOEC');
        $translated = $translator->trans('Demander un RdV commercial');
        $translated = $translator->trans('Poser une question technique');
        $translated = $translator->trans('Divers');
        $translated = $translator->trans('Votre nom *');
        $translated = $translator->trans('Votre e-mail *');
        $translated = $translator->trans('Votre message *');
        $translated = $translator->trans('Envoyer');

        $clients = new Leads();
        $form = $this->createForm(UserRegistrationFormType::class, $clients, [

            'method' => 'GET'
        ]);

        $demande = null;
        $form->get('leads_message')->setData($demande);
        //////////////////////
        //Handle the request//
        //////////////////////
        $form->handleRequest($request);
        $submited = false;
      
        if ($form->isSubmitted() && $form->isValid()) {
           $session=$request->getSession();
           $locale = $session ->get('_locale');

                $clients->setCreated(new \DateTime())
                ->setLeadsLang($locale);

            ////////////////////////
            // saving to database //
            ////////////////////////
            $em = $this->getDoctrine()->getManager();
            $em->persist($clients);
            $em->flush();
            $message=$translator->trans('Votre message a bien été envoyé');

            $notification->notify($clients);

            $subject = $form->getData()->getLeadsSujet();
            if ($subject == 'FLYER') {
                //$notification->sendFlyer($clients);
            }

            $this->addFlash('success', $message);
            //return $this->redirectToRoute('contact');

            $form = $this->createForm(UserRegistrationFormType::class);
            $submited = true;

        }
        return $this->render('tekxia/contact.html.twig', [
            'registrationForm' => $form->createView(),
            'contactSaved' => $submited

        ]);

    }

    /**
     * @Route("/mentions", name="mentions")
     */
    public function mentions()
    {

        return $this->render('tekxia/legal.html.twig', [

        ]);
    }

    /**
     * @Route("/cgv", name="cgv")
     */
    public function cgv()
    {

        return $this->render('tekxia/cgv.html.twig', [

        ]);
    }

    /**
     * @Route("/change-locale/{locale}", name="change_locale")
     */
    public function changeLocale($locale, Request $request)
    {
        //On stocke la langue demandée dans la session
        $request->getSession()->set('_locale', $locale);
        //On revient sur la page précédente
        return $this->redirect($request->headers->get('referer'));

    }
}
`

**services.yaml**

`parameters:
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    app.path.featured_images: /uploads/images/featured
    app.locales: [en, fr]
    locale: fr

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventSubscriber\LocaleSubscriber:
        arguments: ['%kernel.default_locale%']
        # uncomment the next line if you are not using autoconfigure
        # tags: [kernel.event_subscriber]
`

**translation.yaml**

`framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'`

**UserLocaleSubscriber.php**

`<?php

namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Security\Http\Event\InteractiveLoginEvent;
use Symfony\Component\Security\Http\SecurityEvents;

/**
 * Stores the locale of the user in the session after the
 * login. This can be used by the LocaleSubscriber afterwards.
 */
class UserLocaleSubscriber implements EventSubscriberInterface
{
    private $session;

    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }

    public function onInteractiveLogin(InteractiveLoginEvent $event)
    {
        $user = $event->getAuthenticationToken()->getUser();

        if (null !== $user->getLocale()) {
            $this->session->set('_locale', $user->getLocale());
        }
    }

    public static function getSubscribedEvents()
    {
        return [
            SecurityEvents::INTERACTIVE_LOGIN => 'onInteractiveLogin',
        ];
    }
}`

**\LocaleSubscriber.php**

`<?php

namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\KernelEvents;

class LocaleSubscriber implements EventSubscriberInterface
{
    private $defaultLocale;

    public function __construct($defaultLocale ='en')
    {
        $this->defaultLocale = $defaultLocale;
    }

    public function onKernelRequest(RequestEvent $event)
    {
        $request = $event->getRequest();
        if (!$request->hasPreviousSession()) {
            return;
        }
        // try to see if the locale has been set as a _locale routing parameter
        if ($locale = $request->query->get('_locale')) {
            $request->setLocale($locale);
        } else {
            // if no explicit locale has been set on this request, use one from the session
            $request->setLocale($request->getSession()->get('_locale', $this->defaultLocale));
        }
    }

    public static function getSubscribedEvents()
    {
        return [
            // must be registered before (i.e. with a higher priority than) the default Locale listener
            KernelEvents::REQUEST => [['onKernelRequest', 20]],
        ];
    }
}`

 **base.html.twig**

` <ul class="navbar-nav pl-4 ">
                {% for locale in locales %}
                    {% if locale != app.request.locale %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('change_locale', {'locale':locale}) }}">
                                <img src="{{ asset('images/'~locale~'.svg') }}" width="35" height="auto"
                                     alt="{{ locale }}">
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}`

Je suis conscient que c'est un peu lourd mais j'espère avoir été assez précis.

Merci d'avance pour votre aide. 

Jérôme

**Comment by mathilderenversade** [comment]
Salut Jerôme, j'ai bien pris connaissance de ton issue. Bravo pour la précision.
As-tu un fichier config/routes.yaml ?
Quel est son contenu ?
As-tu mis en place ceci  ? https://symfony.com/doc/4.3/translation/locale.html

**Comment by jpicard22** [comment]
Merci Mathilde, oui j'ai mon dossier route.yaml et le voici.

`#index:
#    path: /
#    controller: App\Controller\DefaultController::index

captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"
`

Mais je crois que j'ai un autre fichier qui gère mes routes. Je regarde...

**Comment by jpicard22** [comment]
je vais compléter mon fichier route. Merci, je te retiens au courant
